In [346]:
from pathlib import Path
import duckdb
import numpy as np
import pandas as pd
con = duckdb.connect("warehouse.duckdb")

In [347]:
con.execute("""
    DROP TABLE IF EXISTS fact_sales;
    DROP TABLE IF EXISTS dim_time;
    DROP TABLE IF EXISTS dim_item;
    DROP TABLE IF EXISTS dim_location;
            
    -- DIMENSIONES — atributos descriptivos y jerarquías
    CREATE TABLE dim_time (
    time_key INTEGER PRIMARY KEY,
    day DATE, month VARCHAR, quarter VARCHAR, year INTEGER );
            
    CREATE TABLE dim_item (
    item_key INTEGER PRIMARY KEY,
    item_name VARCHAR, brand VARCHAR, category VARCHAR );
            
    CREATE TABLE dim_location (
    loc_key INTEGER PRIMARY KEY,
    city VARCHAR, state VARCHAR, country VARCHAR );
    -- HECHOS — claves foraneas + medidas numericas
            
    CREATE TABLE fact_sales (
    time_key INTEGER REFERENCES dim_time(time_key),
    item_key INTEGER REFERENCES dim_item(item_key),
    loc_key INTEGER REFERENCES dim_location(loc_key),
    dollars_sold DECIMAL(12,2),
    units_sold INTEGER );
""")

In [348]:
con.execute("""
    INSERT INTO dim_time SELECT * FROM read_csv_auto('data/dim_time.csv');
    INSERT INTO dim_item SELECT * FROM read_csv_auto('data/dim_item.csv');
    INSERT INTO dim_location SELECT * FROM read_csv_auto('data/dim_location.csv');
    INSERT INTO fact_sales SELECT * FROM read_csv_auto('data/fact_sales.csv');
""")

In [349]:
con.execute("""
    DROP VIEW IF EXISTS v_sales;
    CREATE VIEW v_sales AS
    SELECT t.year, t.quarter, t.month, i.category, i.item_name, l.country, f.dollars_sold, f.units_sold
    FROM fact_sales f
    JOIN dim_time t USING (time_key)
    JOIN dim_item i USING (item_key)
    JOIN dim_location l USING (loc_key);
""")

Roll-up (drill-up) y Drill-down

In [350]:
con.execute("""
    SELECT country, SUM(dollars_sold), SUM(units_sold) FROM v_sales GROUP BY country;
    SELECT year, month, quarter, SUM(dollars_sold), SUM(units_sold) FROM v_sales
    GROUP BY year, month, quarter;
""")

Slice & dice

In [351]:
con.execute("""
    SELECT category, SUM(dollars_sold), SUM(units_sold) FROM v_sales
    WHERE country = 'USA' GROUP BY category;
""")

Pivot (rotate)

In [352]:
con.execute("""
    PIVOT v_sales ON country USING SUM(dollars_sold) GROUP BY category;
""")

In [353]:
cube_df = con.execute("""
    SELECT t.year, l.country, i.category,
        SUM(f.dollars_sold) AS dollars_sold,
        SUM(f.units_sold) AS units_sold
    FROM fact_sales f
    JOIN dim_time t ON f.time_key = t.time_key
    JOIN dim_location l ON f.loc_key = l.loc_key
    JOIN dim_item i ON f.item_key = i.item_key
    GROUP BY CUBE (t.year, l.country, i.category)
""").df()
cube_df

    year   country     category  dollars_sold  units_sold
0   <NA>       NaN          NaN    1087931.42     38896.0
1   2025       NaN          NaN    1087931.42     38896.0
2   2025       USA          NaN     371309.46     11613.0
3   2025    Mexico          NaN     382387.89     14230.0
4   2025     Chile          NaN     149523.18      5246.0
5   2025  Colombia          NaN     184710.89      7807.0
6   2025    Mexico  Electronics      51265.67      1865.0
7   2025     Chile      Grocery      46117.75      1632.0
8   2025       USA       Beauty      78809.76      2665.0
9   2025     Chile         Home      25176.05       822.0
10  2025       USA       Sports      65871.35      2004.0
11  2025    Mexico         Home      61481.04      2217.0
12  2025     Chile  Electronics      19559.61       686.0
13  2025    Mexico      Grocery     122737.79      4596.0
14  2025       USA      Grocery     114985.81      3601.0
15  2025    Mexico       Sports      71760.33      2600.0
16  2025       USA         Home      64135.93      1927.0
17  2025     Chile       Beauty      32357.55      1197.0
18  2025       USA  Electronics      47506.61      1416.0
19  2025     Chile       Sports      26312.22       909.0
20  2025    Mexico       Beauty      75143.06      2952.0
21  2025  Colombia  Electronics      21901.29       918.0
22  2025  Colombia       Sports      30887.24      1266.0
23  2025  Colombia       Beauty      40182.81      1811.0
24  2025       NaN       Beauty     226493.18      8625.0
25  2025       NaN         Home     182551.20      6250.0
26  2025       NaN      Grocery     343822.72     12357.0
27  2025       NaN       Sports     194831.14      6779.0
28  2025       NaN  Electronics     140233.18      4885.0
29  <NA>       USA          NaN     371309.46     11613.0
30  2025  Colombia         Home      31758.18      1284.0
31  2025  Colombia      Grocery      59981.37      2528.0
32  <NA>     Chile          NaN     149523.18      5246.0
33  <NA>  Colombia          NaN     184710.89      7807.0
34  <NA>       USA       Sports      65871.35      2004.0
35  <NA>     Chile       Sports      26312.22       909.0
36  <NA>       USA  Electronics      47506.61      1416.0
37  <NA>     Chile  Electronics      19559.61       686.0
38  <NA>    Mexico          NaN     382387.89     14230.0
39  <NA>    Mexico         Home      61481.04      2217.0
40  <NA>    Mexico      Grocery     122737.79      4596.0
41  <NA>  Colombia  Electronics      21901.29       918.0
42  <NA>       USA      Grocery     114985.81      3601.0
43  <NA>     Chile      Grocery      46117.75      1632.0
44  <NA>       USA         Home      64135.93      1927.0
45  <NA>     Chile         Home      25176.05       822.0
46  <NA>    Mexico  Electronics      51265.67      1865.0
47  <NA>  Colombia         Home      31758.18      1284.0
48  <NA>  Colombia      Grocery      59981.37      2528.0
49  <NA>  Colombia       Beauty      40182.81      1811.0
50  <NA>    Mexico       Sports      71760.33      2600.0
51  <NA>       NaN       Beauty     226493.18      8625.0
52  <NA>  Colombia       Sports      30887.24      1266.0
53  <NA>    Mexico       Beauty      75143.06      2952.0
54  <NA>       NaN         Home     182551.20      6250.0
55  <NA>       NaN      Grocery     343822.72     12357.0
56  <NA>       NaN       Sports     194831.14      6779.0
57  <NA>     Chile       Beauty      32357.55      1197.0
58  <NA>       USA       Beauty      78809.76      2665.0
59  <NA>       NaN  Electronics     140233.18      4885.0

In [354]:
rollup_df = con.execute("""
    SELECT year, country, category, SUM(dollars_sold) AS dollars_sold, SUM(units_sold) AS units_sold
    FROM v_sales
    GROUP BY ROLLUP (year, country, category)
""").df()
rollup_df

    year   country     category  dollars_sold  units_sold
0   <NA>       NaN          NaN    1087931.42     38896.0
1   2025       NaN          NaN    1087931.42     38896.0
2   2025     Chile          NaN     149523.18      5246.0
3   2025    Mexico          NaN     382387.89     14230.0
4   2025       USA          NaN     371309.46     11613.0
5   2025       USA       Sports      65871.35      2004.0
6   2025    Mexico         Home      61481.04      2217.0
7   2025     Chile  Electronics      19559.61       686.0
8   2025    Mexico      Grocery     122737.79      4596.0
9   2025  Colombia          NaN     184710.89      7807.0
10  2025       USA  Electronics      47506.61      1416.0
11  2025     Chile       Sports      26312.22       909.0
12  2025    Mexico       Beauty      75143.06      2952.0
13  2025  Colombia         Home      31758.18      1284.0
14  2025  Colombia      Grocery      59981.37      2528.0
15  2025    Mexico  Electronics      51265.67      1865.0
16  2025     Chile      Grocery      46117.75      1632.0
17  2025       USA       Beauty      78809.76      2665.0
18  2025     Chile         Home      25176.05       822.0
19  2025  Colombia  Electronics      21901.29       918.0
20  2025       USA      Grocery     114985.81      3601.0
21  2025    Mexico       Sports      71760.33      2600.0
22  2025       USA         Home      64135.93      1927.0
23  2025     Chile       Beauty      32357.55      1197.0
24  2025  Colombia       Beauty      40182.81      1811.0
25  2025  Colombia       Sports      30887.24      1266.0

¿Cuál es más rápida? Mide con %timeit o time.perf_counter().
• ¿Cuál se puede particionar? ¿Por qué SUM se puede agregar incrementalmente y MEDIAN no?
• Si tuvieras 1,000 millones de filas, ¿cuál materializarías y cuál calcularías al vuelo? ¿Por qué?

In [355]:
groupset_sums_df = con.execute("""
    SELECT year, country, SUM(dollars_sold), SUM(units_sold)
    FROM v_sales
    GROUP BY GROUPING SETS ((year), (country), (year,country), ());
""").df()
groupset_sums_df

   year   country  sum(dollars_sold)  sum(units_sold)
0  2025       NaN         1087931.42          38896.0
1  <NA>       USA          371309.46          11613.0
2  <NA>  Colombia          184710.89           7807.0
3  2025    Mexico          382387.89          14230.0
4  2025       USA          371309.46          11613.0
5  <NA>    Mexico          382387.89          14230.0
6  2025     Chile          149523.18           5246.0
7  <NA>       NaN         1087931.42          38896.0
8  2025  Colombia          184710.89           7807.0
9  <NA>     Chile          149523.18           5246.0

In [356]:
groupset_median_df = con.execute("""
    SELECT year, country,   MEDIAN(dollars_sold), MEDIAN(units_sold)
    FROM v_sales
    GROUP BY GROUPING SETS ((year), (country), (year,country), ());
""").df()
groupset_median_df

   year   country  median(dollars_sold)  median(units_sold)
0  <NA>  Colombia                 75.83                 3.0
1  <NA>     Chile                 93.42                 3.0
2  <NA>       USA                104.48                 3.0
3  2025     Chile                 93.42                 3.0
4  2025       USA                104.48                 3.0
5  2025  Colombia                 75.83                 3.0
6  2025    Mexico                 90.17                 4.0
7  2025       NaN                 91.31                 3.0
8  <NA>    Mexico                 90.17                 4.0
9  <NA>       NaN                 91.31                 3.0

In [ ]:
iceberg_df = con.execute("""
        select country, month, item_name, SUM(dollars_sold) AS dollars_sold
        FROM v_sales 
        Group by cube (country, month, item_name)
        having SUM(dollars_sold) >= 50000
""").df()
iceberg_df

     country month item_name  dollars_sold
0        NaN     4      None      91053.99
1        NaN     3      None      91386.51
2        USA   NaN      None     371309.46
3        NaN     6      None      89586.91
4        NaN     7      None      91463.75
5        NaN     5      None      85397.28
6        NaN     9      None      84327.79
7        NaN     2      None      81791.69
8      Chile   NaN      None     149523.18
9        NaN     1      None      83436.45
10  Colombia   NaN      None     184710.89
11       NaN   NaN      None    1087931.42
12       NaN     8      None      88701.09
13       NaN    12      None     111041.98
14       NaN    11      None      97816.87
15    Mexico   NaN      None     382387.89
16       NaN    10      None      91927.11